---
ansible_user: root
ansible_ssh_private_key_file: >-
  {{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/simpleproxy_ed25519

cloudflare_zero_trust_organization: >-
  {{ lookup('ansible.builtin.env', 'CLOUDFLARE_ZERO_TRUST_ORGANIZATION') }}
cloudflare_access_client_id: >-
  {{ lookup('ansible.builtin.env', 'CLOUDFLARE_ACCESS_CLIENT_ID') }}
cloudflare_access_client_secret: >-
  {{ lookup('ansible.builtin.env', 'CLOUDFLARE_ACCESS_CLIENT_SECRET') }}
cloudflare_mesh_backend_checks:
  - host: 172.31.240.1
    port: 30500
  - host: 172.31.240.4
    port: 30500
simpleproxy_retired_backend_addresses:
  - 10.0.0.108
  - 10.0.0.110
simpleproxy_required_backend_addresses:
  - 172.31.240.1
  - 172.31.240.4

simpleproxy_admin_user: proxyadmin
simpleproxy_admin_authorized_keys: []
simpleproxy_admin_passwordless_sudo: true

simpleproxy_user: simpleproxy
simpleproxy_group: simpleproxy
simpleproxy_home: /opt/simpleproxy
simpleproxy_jar_path: /opt/simpleproxy/SimpleProxy.jar
simpleproxy_jar_url: https://repo.azisaba.net/repository/maven-public/net/azisaba/simpleproxy/proxy/2.1.1/proxy-2.1.1-all.jar
simpleproxy_jar_checksum: sha256:7828546a7a4f6cb9a4183c755cf6173ba4b388ab301167cb681438e520f796a9
simpleproxy_java_package: openjdk-17-jre-headless
simpleproxy_java_opts: "-Xms64m -Xmx512m"
simpleproxy_port: 25565

simpleproxy_config_repo: git@github.com:azisaba/relay-server-config.git
simpleproxy_config_branch: generated
simpleproxy_config_commit: "cd222a4598c0d387beacca501fcec16fde8ae669"
simpleproxy_config_source: ip-deny-list/generated/simpleproxy-config.yml
simpleproxy_config_path: /opt/simpleproxy/config.yml
simpleproxy_config_checkout_dir: >-
  {{ lookup('ansible.builtin.env', 'RUNNER_TEMP') | default('/tmp', true) }}/relay-server-config
